server:
  port: 8002
spring:
  application:
    name: PROVIDER-TICKET
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db
    username: root
    password: root

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP
#    ip-address: 192.168.7.127
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
#    map-underscore-to-camel-case: true
#
#
#sharding:
#  jdbc:
#    datasource:
#      names: master0,master0slave0,master0slave1
#
#      master0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/db?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        username: root
#        password: root
#      master0slave0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/db_slave0?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        username: root
#        password: root
#      master0slave1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/db_slave1?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#        username: root
#        password: root
#
#    config:
#      sharding:
#        default-data-source-name: master0
#        default-database-strategy:
#          inline:
#            sharding-column: id
#            algorithm-expression: master$->{id % 2}
#        tables:
#          goods:
#            actual-data-nodes: master$->{0..1}.id$->{0..1}
#            table-strategy:
#              inline:
#                sharding-column: goods_type
#                algorithm-expression: goods_$->{goods_type % 2}
#            key-generator:
#              column: id
#              type: SNOWFLAKE

logging:
  level:
    com:
      pm:
        providerticket:
          mapper: debug