spring:
  application:
    name: CONSUMER-USER
#  mvc:
#    view:
#      prefix: /WEB-INF/jsp
#      suffix: .jsp

server:
  port: 8003

eureka:
  instance:
    prefer-ip-address: true #注册服务的时候使用服务的IP
#    ip-address: 192.168.7.127
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

hystrix:
  command:
    default:  #default全局有效，service id指定应用有效
      execution:
        timeout:
          #如果enabled设置为 false，则请求超时交给ribbon控制,为 true ,则超时作为熔断根据
          enabled: false
        isolation:
          thread:
            timeoutInMilliseconds: 5000 #断路器超时时间，默认1000ms

ribbon:
  ConnectTimeout: 5000 # 连接超时时间(ms)
  ReadTimeout: 5000 # 通信超时时间(ms)
  MaxAutoRetries: 0 # 同一实例的重试次数
  MaxAutoRetriesNextServer: 0 # 同一服务不同实例的重试次数
  OkToRetryOnAllOperations: true # 是否对所有操作重试